/**
 * useExport — PNG and SVG export logic for the mind map.
 *
 * Both formats are generated by reconstructing a pure SVG from layout data
 * (flatNodes + links) — no DOM capture, no CSS variable dependencies.
 * PNG rasterizes that SVG via an offscreen <canvas> element.
 */
import { save } from '@tauri-apps/plugin-dialog'
import { writeFile } from '@tauri-apps/plugin-fs'
import { useMindmapStore } from '../stores/mindmap'
import type { MindNode } from '../types/mindmap'
import { useTheme } from './useTheme'

// ── Types shared with ExportDialog ────────────────────────────────────────────

export type ExportFormat  = 'png' | 'svg'
export type ExportRange   = 'full' | 'selected'
export type ExportBg      = 'transparent' | 'white' | 'custom' | 'canvas'
export interface ExportOptions {
  format:     ExportFormat
  range:      ExportRange
  background: ExportBg
  customBg:   string        // hex color used when background === 'custom'
  width:      number        // PNG only; max output pixels (width); ignored for SVG
  height:     number        // PNG only; max output pixels (height); ignored for SVG
}

export interface ExportData {
  stageEl:   HTMLElement
  flatNodes: LayoutNodeExport[]
  links:     LinkExport[]
}

export interface LayoutNodeExport {
  id:       string
  text:     string
  depth:    number
  x:        number   // left edge
  y:        number   // center Y (for radial/tree-lr) or center Y for tree-tb
  w:        number   // effective width
  h:        number
  parentId: string | null
  side:     string
  // resolved styles
  bg:          string
  textColor:   string
  bold:        boolean
  italic:      boolean
  underline:   boolean
  strikethrough: boolean
  borderWidth: number
  borderColor: string
  shape:       string
  fontSize:    number
  fontWeight:  string
}

export interface LinkExport {
  id:       string
  d:        string
  parentId: string
}

// ── Last-used path storage ─────────────────────────────────────────────────────
const LAST_DIR_KEY = 'export_last_dir'
function getLastDir(): string | undefined {
  return localStorage.getItem(LAST_DIR_KEY) ?? undefined
}
function setLastDir(path: string) {
  // Extract directory from a file path
  const sep = path.includes('/') ? '/' : '\\'
  const parts = path.split(sep)
  parts.pop()
  localStorage.setItem(LAST_DIR_KEY, parts.join(sep))
}

// ── Main composable ────────────────────────────────────────────────────────────
export function useExport() {
  const store = useMindmapStore()
  const { theme } = useTheme()

  // Resolve CSS variable values at runtime based on current theme
  function cssVar(name: string): string {
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  }

  function resolvedColor(varName: string, fallback: string): string {
    const v = cssVar(varName)
    return v || fallback
  }

  // Default node colors per depth and theme
  function defaultBg(depth: number): string {
    if (depth === 0) return resolvedColor('--color-accent', '#4f8ef7')
    if (depth === 1) return resolvedColor('--color-surface-2', '#3a3a3c')
    return resolvedColor('--color-surface', '#2c2c2e')
  }

  function defaultTextColor(depth: number): string {
    if (depth === 0) return '#ffffff'
    return resolvedColor('--color-text-primary', '#f5f5f7')
  }

  // ── Compute bounding box of a set of layout nodes ──────────────────────────
  function computeBounds(nodes: LayoutNodeExport[], padding = 40): {
    minX: number; minY: number; maxX: number; maxY: number
    width: number; height: number
  } {
    if (nodes.length === 0) return { minX: 0, minY: 0, maxX: 400, maxY: 300, width: 400, height: 300 }
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
    for (const n of nodes) {
      const left  = n.x
      const top   = n.y - n.h / 2
      const right = n.x + n.w
      const bot   = n.y + n.h / 2
      if (left  < minX) minX = left
      if (top   < minY) minY = top
      if (right > maxX) maxX = right
      if (bot   > maxY) maxY = bot
    }
    return {
      minX: minX - padding,
      minY: minY - padding,
      maxX: maxX + padding,
      maxY: maxY + padding,
      width:  maxX - minX + padding * 2,
      height: maxY - minY + padding * 2,
    }
  }

  // ── Filter nodes to the selected subtree ──────────────────────────────────
  function collectSubtree(rootId: string, all: LayoutNodeExport[]): Set<string> {
    const ids = new Set<string>()
    const queue = [rootId]
    while (queue.length) {
      const id = queue.shift()!
      ids.add(id)
      for (const n of all) {
        if (n.parentId === id) queue.push(n.id)
      }
    }
    return ids
  }

  // ── Resolve node bg when it uses CSS var fallbacks ─────────────────────────
  function resolveNodeBg(bg: string, depth: number): string {
    if (bg.startsWith('var(')) return defaultBg(depth)
    return bg
  }

  // ── Background color for the export canvas ─────────────────────────────────
  function resolveExportBg(opts: ExportOptions): string | null {
    if (opts.background === 'transparent') return null
    if (opts.background === 'white')       return '#ffffff'
    if (opts.background === 'custom')      return opts.customBg
    // 'canvas' — use the current map's background color
    return store.canvasBg.color ?? (theme.value === 'dark' ? '#141416' : '#ede8e0')
  }

  // ── Build a pure SVG string from layout data ─────────────────────────────
  function buildSvgString(
    nodes: LayoutNodeExport[],
    linksToRender: LinkExport[],
    bgColor: string | null,
  ): string {
    const bounds    = computeBounds(nodes)
    const ls        = store.lineStyle
    const dashArray = ls.type === 'dashed' ? '6 3' : ls.type === 'dotted' ? '2 3' : 'none'

    const HEX_INDENT = 14
    const RADIUS_MD  = 8
    const RADIUS_LG  = 12

    function hexPoints(w: number, h: number): string {
      const pts: [number, number][] = [
        [HEX_INDENT, 0],
        [w - HEX_INDENT, 0],
        [w, h / 2],
        [w - HEX_INDENT, h],
        [HEX_INDENT, h],
        [0, h / 2],
      ]
      return pts.map(([x, y]) => `${x},${y}`).join(' ')
    }

    const dx = -bounds.minX
    const dy = -bounds.minY

    let svgBody = ''

    // Background rect
    if (bgColor) {
      svgBody += `  <rect x="0" y="0" width="${bounds.width}" height="${bounds.height}" fill="${esc(bgColor)}"/>\n`
    }

    // Links
    for (const link of linksToRender) {
      const shiftedD = shiftSvgPath(link.d, dx, dy)
      svgBody += `  <path d="${esc(shiftedD)}" fill="none" stroke="${esc(ls.color)}" stroke-width="${ls.width}" stroke-dasharray="${dashArray}" stroke-linecap="round"/>\n`
    }

    // Nodes
    for (const n of nodes) {
      const nx  = n.x + dx
      const ny  = n.y - n.h / 2 + dy
      const nw  = n.w
      const nh  = n.h
      const bg  = resolveNodeBg(n.bg, n.depth)
      const tc  = n.textColor.startsWith('var(') ? defaultTextColor(n.depth) : n.textColor
      const bw  = n.borderWidth
      const bc  = n.borderColor.startsWith('var(') ? resolvedColor('--color-border', 'rgba(255,255,255,0.08)') : n.borderColor
      const textDeco = [n.underline && 'underline', n.strikethrough && 'line-through'].filter(Boolean).join(' ') || 'none'

      // background shape
      if (n.shape === 'hexagon') {
        const pts = hexPoints(nw, nh)
        const stroke = bw > 0 ? `stroke="${esc(bc)}" stroke-width="${bw}"` : 'stroke="none"'
        svgBody += `  <polygon transform="translate(${nx.toFixed(1)},${ny.toFixed(1)})" points="${pts}" fill="${esc(bg)}" ${stroke}/>\n`
      } else if (n.shape === 'ellipse') {
        const rx = nw / 2, ry = nh / 2
        const cx = nx + rx, cy = ny + ry
        const stroke = bw > 0 ? `stroke="${esc(bc)}" stroke-width="${bw}"` : 'stroke="none"'
        svgBody += `  <ellipse cx="${cx.toFixed(1)}" cy="${cy.toFixed(1)}" rx="${rx.toFixed(1)}" ry="${ry.toFixed(1)}" fill="${esc(bg)}" ${stroke}/>\n`
      } else {
        let rx = 0
        if (n.shape === 'rounded') rx = RADIUS_MD
        else if (n.shape === 'pill') rx = nh / 2
        if (n.depth === 0 && n.shape === 'rounded') rx = RADIUS_LG
        const stroke = bw > 0 ? `stroke="${esc(bc)}" stroke-width="${bw}"` : 'stroke="none"'
        svgBody += `  <rect x="${nx.toFixed(1)}" y="${ny.toFixed(1)}" width="${nw.toFixed(1)}" height="${nh.toFixed(1)}" rx="${rx}" fill="${esc(bg)}" ${stroke}/>\n`
      }

      // text
      const fontWeight  = n.bold   ? 'bold' : n.fontWeight
      const fontStyle   = n.italic ? 'italic' : 'normal'
      const fontSize    = n.fontSize
      const lines       = n.text.split('\n')
      const lineH       = fontSize * 1.4
      const totalTextH  = lines.length * lineH
      const textStartY  = ny + nh / 2 - totalTextH / 2 + lineH * 0.8

      for (let i = 0; i < lines.length; i++) {
        const ly = textStartY + i * lineH
        const lx = nx + nw / 2
        svgBody += `  <text x="${lx.toFixed(1)}" y="${ly.toFixed(1)}" text-anchor="middle" font-family="system-ui,-apple-system,sans-serif" font-size="${fontSize}" font-weight="${fontWeight}" font-style="${fontStyle}" fill="${esc(tc)}" text-decoration="${textDeco}">${escXml(lines[i])}</text>\n`
      }
    }

    return [
      `<svg xmlns="http://www.w3.org/2000/svg" width="${bounds.width.toFixed(0)}" height="${bounds.height.toFixed(0)}" viewBox="0 0 ${bounds.width.toFixed(0)} ${bounds.height.toFixed(0)}">`,
      svgBody,
      `</svg>`,
    ].join('\n')
  }

  // ── Rasterize an SVG string to PNG bytes via offscreen <canvas> ───────────
  // The canvas is canvasW × canvasH. The SVG content is drawn at (offsetX, offsetY)
  // scaled to drawW × drawH (content fits inside canvas, centered, aspect ratio preserved).
  function svgTopng(
    svgStr: string,
    canvasW: number, canvasH: number,
    bgColor: string | null,
    drawW: number, drawH: number,
    offsetX: number, offsetY: number,
  ): Promise<Uint8Array> {
    const blob = new Blob([svgStr], { type: 'image/svg+xml' })
    const url  = URL.createObjectURL(blob)
    return new Promise((resolve, reject) => {
      const img = new Image()
      img.onload = () => {
        const canvas = document.createElement('canvas')
        canvas.width  = canvasW
        canvas.height = canvasH
        const ctx = canvas.getContext('2d')!
        // Fill background (entire canvas, including letterbox areas)
        if (bgColor) {
          ctx.fillStyle = bgColor
          ctx.fillRect(0, 0, canvasW, canvasH)
        }
        // Draw content centered
        ctx.drawImage(img, offsetX, offsetY, drawW, drawH)
        URL.revokeObjectURL(url)
        canvas.toBlob(b => {
          if (!b) { reject(new Error('canvas.toBlob returned null')); return }
          b.arrayBuffer().then(buf => resolve(new Uint8Array(buf))).catch(reject)
        }, 'image/png')
      }
      img.onerror = (_e) => {
        URL.revokeObjectURL(url)
        reject(new Error('Failed to load SVG into Image element'))
      }
      img.src = url
    })
  }

  // ── PNG export — renders via SVG → offscreen canvas ───────────────────────
  async function exportPng(data: ExportData, opts: ExportOptions): Promise<string | null> {
    let nodes = data.flatNodes
    let linksToRender = data.links

    if (opts.range === 'selected' && store.selectedId) {
      const ids = collectSubtree(store.selectedId, nodes)
      nodes = nodes.filter(n => ids.has(n.id))
      linksToRender = linksToRender.filter(l => ids.has(l.parentId))
    }

    const bgColor = resolveExportBg(opts)
    const svgStr  = buildSvgString(nodes, linksToRender, bgColor)
    const bounds  = computeBounds(nodes)

    // Scale content to fit inside opts.width × opts.height, preserving aspect ratio.
    // The canvas is always exactly opts.width × opts.height; content is centered.
    const scale  = Math.min(opts.width / bounds.width, opts.height / bounds.height)
    const drawW  = Math.round(bounds.width  * scale)
    const drawH  = Math.round(bounds.height * scale)
    const offsetX = Math.round((opts.width  - drawW) / 2)
    const offsetY = Math.round((opts.height - drawH) / 2)

    const bytes = await svgTopng(svgStr, opts.width, opts.height, bgColor, drawW, drawH, offsetX, offsetY)
    return await saveFile(bytes, 'png', store.current?.title ?? 'mindmap')
  }

  // ── SVG export ─────────────────────────────────────────────────────────────
  async function exportSvg(data: ExportData, opts: ExportOptions): Promise<string | null> {
    let nodes = data.flatNodes
    let linksToRender = data.links

    if (opts.range === 'selected' && store.selectedId) {
      const ids = collectSubtree(store.selectedId, nodes)
      nodes = nodes.filter(n => ids.has(n.id))
      linksToRender = linksToRender.filter(l => ids.has(l.parentId))
    }

    const bgColor = resolveExportBg(opts)
    const svgStr  = buildSvgString(nodes, linksToRender, bgColor)

    const encoder = new TextEncoder()
    const bytes   = encoder.encode(svgStr)
    return await saveFile(bytes, 'svg', store.current?.title ?? 'mindmap')
  }

  // ── File save via Tauri dialog ─────────────────────────────────────────────
  /** Returns the saved file path on success, null if user cancelled. Throws on real errors. */
  async function saveFile(bytes: Uint8Array, ext: 'png' | 'svg', title: string): Promise<string | null> {
    const defaultName = `${sanitizeFilename(title)}.${ext}`
    const filter = ext === 'png'
      ? [{ name: 'PNG Image', extensions: ['png'] }]
      : [{ name: 'SVG Vector', extensions: ['svg'] }]

    const filePath = await save({
      defaultPath: defaultName,
      filters: filter,
    })

    if (!filePath) return null  // user cancelled

    setLastDir(filePath)
    await writeFile(filePath, bytes)
    return filePath
  }

  // ── Main entry ────────────────────────────────────────────────────────────
  /** Returns the saved file path on success, null if user cancelled. Throws on error. */
  async function runExport(data: ExportData, opts: ExportOptions): Promise<string | null> {
    if (opts.format === 'png') {
      return await exportPng(data, opts)
    } else {
      return await exportSvg(data, opts)
    }
  }

  return { runExport, getLastDir }
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function esc(s: string): string {
  // For SVG attribute values — escape quotes
  return s.replace(/"/g, '&quot;')
}

function escXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function sanitizeFilename(s: string): string {
  return s.replace(/[/\\:*?"<>|]/g, '_').slice(0, 80) || 'mindmap'
}

/**
 * Shift all coordinate values in an SVG path `d` string by (dx, dy).
 * Works with M, L, C commands (which cover all link types generated by MindCanvas).
 */
function shiftSvgPath(d: string, dx: number, dy: number): string {
  // Replace every number pair (x y) in the path data
  // SVG path commands used: M x y, L x y, C x1 y1 x2 y2 x y
  return d.replace(/(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)/g, (_, sx, sy) => {
    const x = parseFloat(sx) + dx
    const y = parseFloat(sy) + dy
    return `${x.toFixed(2)} ${y.toFixed(2)}`
  })
}

// Re-export MindNode so ExportDialog can reference it without circular imports
export type { MindNode }
